"""empty message

Revision ID: 2760f7e58f80
Revises: 
Create Date: 2024-08-08 20:43:56.008182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2760f7e58f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('nin', sa.Integer(), nullable=True),
    sa.Column('bvn', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('utility_bill', sa.String(length=100), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('card_back', sa.Integer(), nullable=False),
    sa.Column('card_expiry', sa.String(length=50), nullable=False),
    sa.Column('transaction_pin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bvn'),
    sa.UniqueConstraint('card_back'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('transaction_pin')
    )
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receiver', sa.String(length=120), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('sender_account', sa.String(length=20), nullable=True),
    sa.Column('receiver_account', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=20), nullable=True),
    sa.Column('electricity_token', sa.String(length=2000), nullable=True),
    sa.Column('session_id', sa.String(length=2000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('transaction_ref')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_history')
    op.drop_table('user')
    # ### end Alembic commands ###
