"""empty message

Revision ID: 2f0926cf39ad
Revises: 7b6e67a80fea
Create Date: 2024-08-13 09:39:00.525849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0926cf39ad'
down_revision = '7b6e67a80fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receiver', sa.String(length=120), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('sender_account', sa.String(length=20), nullable=True),
    sa.Column('receiver_account', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=20), nullable=True),
    sa.Column('electricity_token', sa.String(length=2000), nullable=True),
    sa.Column('session_id', sa.String(length=2000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('narration', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.drop_table('rececipts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rececipts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=120), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('receiver', sa.VARCHAR(length=120), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sender_account', sa.VARCHAR(length=20), nullable=True),
    sa.Column('receiver_account', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('transaction_ref', sa.VARCHAR(length=20), nullable=True),
    sa.Column('electricity_token', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('narration', sa.VARCHAR(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.drop_table('receipts')
    # ### end Alembic commands ###
