"""empty message

Revision ID: 47918f808209
Revises: c23e7925b667
Create Date: 2024-08-08 21:06:30.620651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47918f808209'
down_revision = 'c23e7925b667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('transaction_pin',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('transaction_pin',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
