"""empty message

Revision ID: 7b6e67a80fea
Revises: 7af37fb2d5fb
Create Date: 2024-08-13 09:25:24.820575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6e67a80fea'
down_revision = '7af37fb2d5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rececipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receiver', sa.String(length=120), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('sender_account', sa.String(length=20), nullable=True),
    sa.Column('receiver_account', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=20), nullable=True, unique=False),
    sa.Column('electricity_token', sa.String(length=2000), nullable=True),
    sa.Column('session_id', sa.String(length=2000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('narration', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rececipts')
    # ### end Alembic commands ###
