"""empty message

Revision ID: c23e7925b667
Revises: cc690a99bb1d
Create Date: 2024-08-08 20:45:38.086308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23e7925b667'
down_revision = 'cc690a99bb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.drop_column('add_new')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_new', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
