"""empty message

Revision ID: cc690a99bb1d
Revises: 2760f7e58f80
Create Date: 2024-08-08 20:45:01.737183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc690a99bb1d'
down_revision = '2760f7e58f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_new', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.drop_column('add_new')

    # ### end Alembic commands ###
