"""Add card_expiry column to User

Revision ID: deb90d934073
Revises: 
Create Date: 2024-08-07 09:28:26.165270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb90d934073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('nin', sa.INTEGER(), nullable=True),
    sa.Column('bvn', sa.INTEGER(), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('utility_bill', sa.VARCHAR(length=100), nullable=True),
    sa.Column('wallet_balance', sa.FLOAT(), nullable=False),
    sa.Column('card_number', sa.INTEGER(), nullable=False),
    sa.Column('card_back', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bvn'),
    sa.UniqueConstraint('card_back'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###
